const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Mutton Curry",
    image: "http://localhost:5000/uploads/mutton-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces with bones",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "Fresh coriander leaves for garnish",
      "2 green chilies - cut long",
      "2 cups warm water"
    ],
    stepsRaw: [
      "Put oil in a big heavy pot on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until they turn golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add mutton pieces and fry on high heat for 8-10 minutes until the meat is brown on all sides.",
      "Add chopped tomatoes and cook for 6-7 minutes until they become soft.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes until the spices smell good.",
      "Add 2 cups of warm water and bring to a boil. Stir well.",
      "Cover the pot and cook on medium-low heat for 45-50 minutes until the mutton is very soft.",
      "Sprinkle garam masala and put fresh coriander leaves and green chilies on top.",
      "Serve hot with naan, roti, or rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A classic and rich Pakistani mutton curry that's perfect for special occasions and pairs wonderfully with naan or rice.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton curry", "pakistani mutton curry", "classic mutton curry", "non vegetarian", "mutton recipe"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Karahi",
    image: "http://localhost:5000/uploads/mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "4 medium tomatoes - chopped small",
      "2 tablespoons ginger - cut into thin strips",
      "2 tablespoons garlic - chopped small",
      "4 green chilies - cut long",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil",
      "Fresh coriander leaves for garnish",
      "1 lemon - juice"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add mutton and fry for 8-10 minutes until the meat turns brown.",
      "Add ginger strips, chopped garlic, and green chilies. Cook for 2-3 minutes until they smell good.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become soft and oil starts to separate.",
      "Add cumin seeds, red chili flakes, black pepper powder, and salt. Mix well.",
      "Cook on high heat for 10-15 minutes while stirring often until the oil comes on top and the meat is soft.",
      "The gravy should be thick and stick to the meat.",
      "Turn off the heat. Add lemon juice and put fresh coriander leaves on top.",
      "Serve right away with hot naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A bold and spicy traditional Pakistani karahi mutton that's perfect for those who love intense flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tomato", "ginger", "garlic", "green chili", "cumin", "red chili flakes", "black pepper", "oil", "salt", "lemon"],
    searchKeywords: ["mutton karahi", "pakistani mutton karahi", "karahi mutton", "non vegetarian", "mutton recipe"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Handi",
    image: "http://localhost:5000/uploads/mutton-handi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "1 cup plain yogurt - beaten until smooth",
      "2 medium onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/4 cup heavy cream",
      "Fresh coriander leaves for garnish",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a handi or heavy pot on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until the meat is brown.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Turn the heat to low. Add beaten yogurt slowly while stirring all the time so it doesn't curdle.",
      "Add 1 cup of warm water. Cover and cook on low heat for 45-50 minutes until the meat is soft and the gravy is thick.",
      "Add cream and garam masala. Cook for 5-7 minutes on low heat.",
      "Put fresh coriander leaves on top and serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A slow-cooked creamy mutton handi that's rich, flavorful, and perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 560,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "yogurt", "dahi", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "cream", "oil", "salt"],
    searchKeywords: ["mutton handi", "handi mutton", "creamy mutton curry", "pakistani handi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Qorma",
    image: "http://localhost:5000/uploads/mutton-qorma.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "1 cup plain yogurt - beaten until smooth",
      "2 medium onions - sliced thin",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil or ghee",
      "Salt as needed",
      "4 whole cloves",
      "2 green cardamom pods",
      "1 small cinnamon stick",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil or ghee in a pan on medium heat. Add whole spices (cloves, cardamom, cinnamon) and cook for 30 seconds until they pop.",
      "Add sliced onions and fry for 7-8 minutes until dark golden brown.",
      "Take out half of the fried onions and keep aside for later.",
      "Add ginger-garlic paste to the remaining onions and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown on all sides.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Turn the heat to low. Add beaten yogurt slowly while stirring all the time so it doesn't curdle.",
      "Add 1 cup of warm water. Cover and cook on low heat for 50-60 minutes until the meat is very soft.",
      "Sprinkle garam masala and put the saved fried onions on top.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 80,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy royal mutton qorma that's perfect for weddings and special occasions.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 580,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "yogurt", "dahi", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "cloves", "cardamom", "cinnamon", "oil", "salt"],
    searchKeywords: ["mutton qorma", "qorma mutton", "mutton korma", "pakistani qorma", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rogan Josh",
    image: "http://localhost:5000/uploads/mutton-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon fennel powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup plain yogurt - beaten",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates from the mixture.",
      "Add turmeric, red chili powder, fennel powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add beaten yogurt and stir well. Cook for 5 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "An aromatic and rich Kashmiri-style mutton rogan josh that's perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "fennel", "garam masala", "yogurt", "oil", "salt"],
    searchKeywords: ["mutton rogan josh", "rogan josh", "kashmiri rogan josh", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Do Pyaza",
    image: "http://localhost:5000/uploads/mutton-do-pyaz.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "3 medium onions - sliced thin (divided)",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add half of the sliced onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Add the remaining raw sliced onions and garam masala.",
      "Cook for 5-7 minutes until the onions are a little soft but still crunchy.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A delicious mutton do pyaza with double the onions, offering a perfect balance of sweet and savory flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 145,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "pyaz", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton do pyaza", "do pyaza mutton", "mutton double onion", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Bhuna",
    image: "http://localhost:5000/uploads/mutton-bhuna.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 7-8 minutes until dark golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 10-12 minutes until brown on all sides.",
      "Add chopped tomatoes and cook for 6-7 minutes until they become dry and the oil separates.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1/2 cup of warm water. Cover and cook on low heat for 45-50 minutes until the meat is soft.",
      "Cook without the lid for the last 10 minutes to dry out the gravy.",
      "The final dish should be thick and dry with the spices sticking to the meat.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A thick and spicy dry bhuna mutton where the masala clings to every piece, perfect with naan.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["mutton bhuna", "bhuna mutton", "dry mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Jalfrezi",
    image: "http://localhost:5000/uploads/mutton-jalfrezi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - boneless, cut into cubes",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 medium capsicum - cut into strips",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton cubes and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Add capsicum strips and cook for 5-7 minutes on high heat until the capsicum is tender but still crunchy.",
      "Sprinkle garam masala and serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A restaurant-style spicy mutton jalfrezi with thick gravy and crunchy capsicum, perfect for special cravings.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "capsicum", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton jalfrezi", "jalfrezi mutton", "mutton capsicum curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "White Mutton Karahi",
    image: "http://localhost:5000/uploads/white-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "1 cup plain yogurt - beaten until smooth",
      "2 tablespoons ginger paste",
      "2 tablespoons garlic paste",
      "4 green chilies - cut long",
      "1 teaspoon white pepper powder",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil",
      "Fresh coriander leaves for garnish",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on medium heat. Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add ginger paste, garlic paste, and green chilies. Cook for 2-3 minutes until they smell good.",
      "Add beaten yogurt and cook on high heat for 5-7 minutes until the oil separates.",
      "Add white pepper powder, black pepper powder, and salt. Mix well.",
      "Add 1 cup of warm water. Cover and cook for 35-40 minutes until the meat is soft.",
      "The gravy should be thick and white in color.",
      "Put fresh coriander leaves on top and serve hot with naan."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A mild and rich creamy white mutton karahi that's perfect for those who prefer less spicy curries.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "yogurt", "dahi", "ginger", "garlic", "green chili", "white pepper", "black pepper", "oil", "salt"],
    searchKeywords: ["white mutton karahi", "white karahi", "creamy mutton karahi", "pakistani karahi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peshawari Mutton Karahi",
    image: "http://localhost:5000/uploads/peshawari-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "4 medium tomatoes - chopped",
      "2 tablespoons ginger - cut into thin strips",
      "2 tablespoons garlic - chopped small",
      "4 green chilies - whole",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil"
    ],
    stepsRaw: [
      "Put oil in a karahi on high heat. Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add ginger strips, chopped garlic, and whole green chilies. Cook for 2-3 minutes.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become soft and the oil separates.",
      "Add cumin seeds, red chili flakes, black pepper powder, and salt. Mix well.",
      "Cook on high heat for 15-20 minutes until the oil separates and the meat is soft.",
      "Do not add water - the tomatoes are enough.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rustic and flavorful Peshawari-style mutton karahi that's cooked without water for intense taste.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tomato", "ginger", "garlic", "green chili", "cumin", "red chili flakes", "black pepper", "oil", "salt"],
    searchKeywords: ["peshawari mutton karahi", "peshawari karahi", "mutton karahi peshawar style", "pakistani karahi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spicy Mutton Karahi",
    image: "http://localhost:5000/uploads/spicy-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "4 medium tomatoes - chopped",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - cut long",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin seeds",
      "1 teaspoon black pepper powder",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a karahi on high heat. Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add ginger-garlic paste and green chilies. Cook for 2-3 minutes.",
      "Add chopped tomatoes and cook for 8-10 minutes until soft and oil separates.",
      "Add red chili powder, cumin seeds, black pepper powder, and salt. Mix well.",
      "Add 1/2 cup warm water and cook for 35-40 minutes until the meat is soft.",
      "The gravy should be thick and very spicy.",
      "Serve hot with naan and yogurt sauce (raita)."
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "An extra spicy mutton karahi for heat lovers, packed with bold and intense flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tomato", "ginger", "garlic", "green chili", "red chili", "cumin", "black pepper", "oil", "salt"],
    searchKeywords: ["spicy mutton karahi", "extra spicy karahi", "hot mutton karahi", "pakistani karahi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dry Mutton Karahi",
    image: "http://localhost:5000/uploads/dry-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - cut long",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a karahi on high heat. Add mutton pieces and fry for 10-12 minutes until golden brown.",
      "Add ginger-garlic paste and green chilies. Cook for 2-3 minutes.",
      "Add chopped tomatoes and cook for 8-10 minutes until completely dry and the oil separates.",
      "Add cumin seeds, red chili powder, and salt. Mix well.",
      "Cook on high heat for 20-25 minutes until the meat is soft and the dish is completely dry.",
      "The spices should cover the meat pieces evenly.",
      "Serve hot with naan and onion salad."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A dry mutton karahi with no gravy, where the masala coats every piece perfectly - ideal with naan.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tomato", "ginger", "garlic", "green chili", "cumin", "red chili", "oil", "salt"],
    searchKeywords: ["dry mutton karahi", "dry karahi", "sukha mutton karahi", "pakistani karahi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Masala",
    image: "http://localhost:5000/uploads/mutton-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "Fresh coriander leaves for garnish",
      "1.5 cups warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates from the mixture.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1.5 cups of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and put fresh coriander leaves on top.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A bold and aromatic spicy mutton masala that's perfect for those who love rich, flavorful curries.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton masala", "masala mutton", "spicy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Tikka Masala",
    image: "http://localhost:5000/uploads/mutton-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton tikka pieces - already cooked",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon kasuri methi (dried fenugreek leaves)",
      "1/2 cup heavy cream",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates from the mixture.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water and bring to a gentle boil.",
      "Add the mutton tikka pieces and cook for 20-25 minutes until well mixed.",
      "Add cream and kasuri methi. Cook for 5-7 minutes on low heat.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A creamy and rich restaurant-style mutton tikka masala that's perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 560,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton tikka", "tikka masala", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "kasuri methi", "cream", "oil", "salt"],
    searchKeywords: ["mutton tikka masala", "tikka masala mutton", "creamy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Butter Masala",
    image: "http://localhost:5000/uploads/mutton-butter-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - boneless, cut into cubes",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1/2 cup heavy cream",
      "2 tablespoons butter",
      "1 teaspoon kasuri methi",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Cook the mutton in a pressure cooker with salt and 1 cup of water until soft. Keep aside.",
      "Put butter and oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 6-7 minutes until the butter separates from the mixture.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked mutton with the water. Cook for 15-20 minutes.",
      "Add cream and kasuri methi. Cook for 5-7 minutes on low heat.",
      "Serve hot with butter naan."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and indulgent creamy butter mutton that's perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 580,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "butter masala", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "cream", "butter", "kasuri methi", "oil", "salt"],
    searchKeywords: ["mutton butter masala", "butter mutton", "creamy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Lababdar",
    image: "http://localhost:5000/uploads/mutton-lababdar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/4 cup heavy cream",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Cook the mutton in a pressure cooker with salt until soft. Keep aside.",
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates from the mixture.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked mutton and 1 cup of water. Cook for 15-20 minutes.",
      "Add cream and garam masala. Cook for 5-7 minutes.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy royal Mughlai mutton lababdar that's perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 560,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "garam masala", "cream", "oil", "salt"],
    searchKeywords: ["mutton lababdar", "lababdar mutton", "royal mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kolhapuri",
    image: "http://localhost:5000/uploads/mutton-kolhapuri.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 tablespoon grated coconut",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add chopped onions and fry for 6-7 minutes until dark brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add red chili powder, turmeric powder, garam masala, salt, and grated coconut. Mix well.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Serve hot with rice or roti."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A very hot and flavorful Kolhapuri-style mutton curry that's perfect for spice lovers.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "red chili", "turmeric", "garam masala", "coconut", "oil", "salt"],
    searchKeywords: ["mutton kolhapuri", "kolhapuri mutton", "spicy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kashmiri Rogan Josh",
    image: "http://localhost:5000/uploads/mutton-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - sliced thin",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon fennel powder",
      "1 teaspoon dry ginger powder",
      "2 teaspoons red chili powder (Kashmiri for red color)",
      "1 teaspoon garam masala",
      "1/2 cup plain yogurt - beaten",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add sliced onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add fennel powder, dry ginger powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add beaten yogurt and stir well. Cook for 5-7 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "An authentic aromatic Kashmiri rogan josh with a beautiful red color and rich flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "ginger", "garlic", "cumin", "fennel", "dry ginger", "red chili", "garam masala", "yogurt", "oil", "salt"],
    searchKeywords: ["kashmiri rogan josh", "rogan josh", "authentic rogan josh", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Easy Rogan Josh",
    image: "http://localhost:5000/uploads/easy-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons rogan josh masala powder",
      "1 teaspoon turmeric powder",
      "1/2 cup plain yogurt - beaten",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add rogan josh masala, turmeric powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add beaten yogurt and stir well. Cook for 5 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A quick and delicious easy rogan josh recipe that doesn't compromise on authentic flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "tomato", "ginger", "garlic", "rogan josh masala", "turmeric", "yogurt", "oil", "salt"],
    searchKeywords: ["easy rogan josh", "simple rogan josh", "quick mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pressure Cooker Rogan Josh",
    image: "http://localhost:5000/uploads/pressure-cooker-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons rogan josh masala",
      "1/2 cup plain yogurt - beaten",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pressure cooker on medium heat. Add chopped onions and fry for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft.",
      "Add rogan josh masala and salt. Mix well and cook for 2 minutes.",
      "Add beaten yogurt and 1/2 cup of warm water. Stir well.",
      "Close the pressure cooker lid and cook for 20-25 minutes (4-5 whistles) until the meat is soft.",
      "Let the pressure go down by itself. Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A quick pressure cooker version of rogan josh that saves time without sacrificing flavor.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "pressure cooker", "onion", "tomato", "ginger", "garlic", "rogan josh masala", "yogurt", "oil", "salt"],
    searchKeywords: ["pressure cooker rogan josh", "quick rogan josh", "instant pot mutton", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kofta Curry",
    image: "http://localhost:5000/uploads/mutton-kofta-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince (keema)",
      "1 medium onion - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 large egg",
      "2 tablespoons breadcrumbs",
      "For gravy: 2 onions, 2 tomatoes",
      "Oil for shallow frying",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "In a bowl, mix mutton mince with chopped onion, ginger-garlic paste, cumin powder, coriander powder, red chili powder, garam masala, egg, breadcrumbs, and salt.",
      "Mix everything well. Make small lemon-sized balls (kofta).",
      "Put oil in a shallow pan on medium heat. Fry the kofta for 5-7 minutes until golden brown on all sides. Take out and keep aside.",
      "For gravy: In the same pan, add more oil if needed. Add chopped onions and fry until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add chopped tomatoes and cook until soft.",
      "Add red chili powder, coriander powder, and salt. Cook for 2-3 minutes.",
      "Add 1 cup of warm water and bring to a boil. Cook for 5-7 minutes.",
      "Add the fried kofta to the gravy and cook for 10-12 minutes.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A delicious and unique mutton kofta curry with tender meatballs in a spicy gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 140,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "kofta", "onion", "tomato", "ginger", "garlic", "cumin", "coriander", "red chili", "garam masala", "egg", "breadcrumbs", "oil", "salt"],
    searchKeywords: ["mutton kofta curry", "kofta curry", "meatball curry", "pakistani kofta", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kofta in Yogurt Gravy",
    image: "http://localhost:5000/uploads/mutton-kofta-in-yogurt-gravy.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 medium onion - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 large egg",
      "For gravy: 1 cup plain yogurt - beaten",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into puree",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Make kofta using the method above and fry until golden. Keep aside.",
      "Put oil in a pan on medium heat. Add chopped onions and fry until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates.",
      "Add cumin powder, red chili powder, and salt. Mix well.",
      "Turn the heat to low. Add beaten yogurt slowly while stirring all the time so it doesn't curdle.",
      "Add 1/2 cup of warm water and bring to a gentle simmer.",
      "Add the fried kofta and cook for 10-12 minutes.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A mild and rich mutton kofta curry in a creamy yogurt sauce, perfect for those who prefer less spice.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 140,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "kofta", "yogurt", "dahi", "onion", "tomato", "ginger", "garlic", "cumin", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton kofta in yogurt gravy", "dahi kofta", "creamy kofta curry", "pakistani kofta", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Nargisi Kofta",
    image: "http://localhost:5000/uploads/nargisi-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "4 large eggs - boiled and peeled",
      "1 medium onion - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 large raw egg",
      "For gravy: 2 onions, 2 tomatoes",
      "Oil for shallow frying",
      "Salt as needed"
    ],
    stepsRaw: [
      "In a bowl, mix mutton mince with chopped onion, ginger-garlic paste, cumin powder, garam masala, raw egg, and salt.",
      "Divide the mince mixture into 4 equal parts.",
      "Take one part and flatten it in your hand. Put a boiled egg in the center and wrap the mince around it completely.",
      "Repeat with the remaining eggs and mince.",
      "Put oil in a shallow pan. Fry the stuffed kofta for 8-10 minutes until golden brown on all sides. Take out and keep aside.",
      "For gravy: In the same pan, add chopped onions and fry until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add chopped tomatoes and cook until soft.",
      "Add red chili powder, coriander powder, and salt. Cook for 2-3 minutes.",
      "Add 1 cup of warm water and bring to a boil. Cook for 5 minutes.",
      "Add the kofta and cook for 10-12 minutes.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A royal nargisi kofta dish with boiled eggs stuffed inside mutton mince, perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "eggs", "nargisi kofta", "onion", "tomato", "ginger", "garlic", "cumin", "garam masala", "oil", "salt"],
    searchKeywords: ["nargisi kofta", "stuffed kofta", "egg kofta", "pakistani kofta", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Malai Kofta",
    image: "http://localhost:5000/uploads/malai-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 medium onion - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1/4 cup heavy cream",
      "1 large egg",
      "For gravy: 2 onions, 2 tomatoes",
      "1/4 cup heavy cream",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Make kofta by mixing mince with onion, ginger-garlic, cumin, garam masala, 1/4 cup cream, egg, and salt.",
      "Shape into balls and shallow fry until golden. Keep aside.",
      "For gravy: Put oil in a pan. Add chopped onions and fry until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomato puree and cook until oil separates.",
      "Add red chili powder and salt. Mix well.",
      "Add 1/2 cup of warm water and bring to a simmer.",
      "Add the remaining 1/4 cup cream and stir well.",
      "Add the fried kofta and cook for 10 minutes.",
      "Serve hot with naan."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and indulgent creamy malai kofta curry that's perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 570,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "kofta", "cream", "malai", "onion", "tomato", "ginger", "garlic", "cumin", "garam masala", "oil", "salt"],
    searchKeywords: ["malai kofta", "creamy kofta", "mutton malai kofta", "pakistani kofta", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rara",
    image: "http://localhost:5000/uploads/mutton-rara.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton pieces - with bones",
      "250g mutton mince (keema)",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add mutton mince and fry for 5-7 minutes until it changes color.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add red chili powder and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A double meat delight mutton rara with both pieces and mince, offering rich texture and flavor.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "mutton mince", "keema", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton rara", "rara mutton", "double meat mutton", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rara Masala",
    image: "http://localhost:5000/uploads/mutton-rara-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton - boneless cubes",
      "250g mutton mince",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton cubes and fry for 8-10 minutes until brown.",
      "Add mutton mince and fry for 5-7 minutes.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add red chili powder and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and serve hot with naan."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A bold and flavorful spicy mutton rara masala with a perfect blend of pieces and mince.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "mutton mince", "keema", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton rara masala", "rara masala", "spicy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hyderabadi Mutton",
    image: "http://localhost:5000/uploads/hyderabadi-mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup plain yogurt - beaten",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add red chili powder, garam masala, and salt. Mix well and cook for 2-3 minutes.",
      "Add beaten yogurt and stir well. Cook for 5 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A rich and aromatic Hyderabadi-style mutton curry that's perfect for a royal meal.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "hyderabadi", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "garam masala", "yogurt", "oil", "salt"],
    searchKeywords: ["hyderabadi mutton", "hyderabadi mutton curry", "nizami mutton", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Punjabi Mutton",
    image: "http://localhost:5000/uploads/punjabi-mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil and butter in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Sprinkle garam masala and serve hot with naan."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A rich and buttery Punjabi-style mutton curry that's full of flavor and perfect with naan.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "punjabi", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "butter", "oil", "salt"],
    searchKeywords: ["punjabi mutton", "punjabi mutton curry", "butter mutton", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kerala Mutton Curry",
    image: "http://localhost:5000/uploads/karela-mutton-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "1 cup thick coconut milk",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "Few curry leaves",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add mustard seeds and curry leaves. Cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add coconut milk and 1/2 cup of warm water. Bring to a gentle simmer.",
      "Cover and cook for 35-40 minutes until the meat is soft.",
      "Serve hot with rice or appam."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A creamy and aromatic Kerala-style coconut mutton curry that's perfect with steamed rice.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "kerala", "coconut milk", "onion", "tomato", "ginger", "garlic", "mustard seeds", "turmeric", "red chili", "curry leaves", "oil", "salt"],
    searchKeywords: ["kerala mutton curry", "coconut mutton curry", "south indian mutton", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chettinad Mutton",
    image: "http://localhost:5000/uploads/Chettinad-Mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon fennel seeds",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon black pepper powder",
      "1/2 cup grated coconut",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Dry roast fennel seeds, cumin seeds, and grated coconut in a pan until they smell good. Grind into a fine paste with a little water. Keep aside.",
      "Put oil in a pan on medium heat. Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add the ground paste, red chili powder, black pepper powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 45-50 minutes until the meat is soft.",
      "Serve hot with rice or roti."
    ],
    difficulty: "Hard",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A very aromatic and spicy Chettinad-style mutton curry that's packed with bold flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "chettinad", "onion", "tomato", "ginger", "garlic", "fennel", "cumin", "red chili", "black pepper", "coconut", "oil", "salt"],
    searchKeywords: ["chettinad mutton", "chettinad mutton curry", "spicy mutton curry", "south indian mutton", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Goan Mutton Curry",
    image: "http://localhost:5000/uploads/goan-mutton-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton - cut into pieces",
      "1 cup thick coconut milk",
      "2 medium onions - chopped small",
      "2 medium tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 tablespoon vinegar",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/2 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton pieces and fry for 8-10 minutes until brown.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add coconut milk, vinegar, and 1/2 cup of warm water. Bring to a gentle simmer.",
      "Cover and cook for 40-45 minutes until the meat is soft.",
      "Serve hot with rice."
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A tangy and spicy Goan-style coconut mutton curry that's perfect with steamed rice.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "goan", "coconut milk", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "turmeric", "vinegar", "oil", "salt"],
    searchKeywords: ["goan mutton curry", "coconut mutton curry", "tangy mutton curry", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Chops Curry",
    image: "http://localhost:5000/uploads/mutton-chops-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton chops",
      "2 medium onions - chopped small",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add mutton chops and fry for 8-10 minutes until brown.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add turmeric, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of warm water. Cover and cook for 35-40 minutes until the chops are soft.",
      "Sprinkle garam masala and serve hot with naan or rice."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A flavorful and tender mutton chops curry that's perfect for a special meal.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "chops curry", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["mutton chops curry", "chops curry", "mutton chop masala", "pakistani mutton curry", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Chops Karahi",
    image: "http://localhost:5000/uploads/mutton-chops-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton chops",
      "4 medium tomatoes - chopped",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - cut long",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon black pepper powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a karahi on high heat. Add mutton chops and fry for 8-10 minutes until brown.",
      "Add ginger-garlic paste and green chilies. Cook for 2-3 minutes.",
      "Add chopped tomatoes and cook for 8-10 minutes until soft and the oil separates.",
      "Add cumin seeds, red chili powder, black pepper powder, and salt. Mix well.",
      "Cook on high heat for 20-25 minutes until the chops are soft.",
      "Serve hot with naan."
    ],
    difficulty: "Hard",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A bold and spicy karahi-style mutton chops that's packed with intense flavors.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "karahi chops", "tomato", "ginger", "garlic", "green chili", "cumin", "red chili", "black pepper", "oil", "salt"],
    searchKeywords: ["mutton chops karahi", "karahi chops", "spicy mutton chops", "pakistani karahi", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Grilled Mutton Chops",
    image: "http://localhost:5000/uploads/grilled-mutton-chops.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton chops",
      "1 cup plain yogurt - beaten",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "2 tablespoons cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Wash the mutton chops and dry them with a cloth. Make small cuts on both sides.",
      "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, cumin powder, garam masala, oil, and salt.",
      "Add the mutton chops and coat well with the mixture.",
      "Cover and keep in the fridge for 4-6 hours or overnight for best results.",
      "Heat oven to 180°C (350°F).",
      "Put the marinated chops on a baking tray with foil.",
      "Bake for 25-30 minutes, turning once in between.",
      "For a charred look, use the broil/grill setting for the last 5 minutes.",
      "Serve hot with mint sauce and onion rings."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Perfectly grilled mutton chops that are tender and flavorful, ideal for parties and gatherings.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "grilled chops", "yogurt", "ginger", "garlic", "red chili", "cumin", "garam masala", "oil", "salt"],
    searchKeywords: ["grilled mutton chops", "oven grilled chops", "mutton chops recipe", "pakistani grilled meat", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrate() {
  try {
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    console.log(' MONGODB_URI:', process.env.MONGODB_URI);
    console.log(' MONGOURI:', process.env.MONGOURI);
    console.log(' MONGO_URI:', process.env.MONGO_URI);
    console.log(' Using URI:', mongoURI ? 'Found' : 'NOT FOUND');
    console.log(' Current directory:', __dirname);
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables. Please check your .env file');
    }
    
    console.log(' Connecting to MongoDB...');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log(' Connected to MongoDB!');
    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(` Added: ${recipe.title}`);
        added++;
      } else {
        console.log(` Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n Migration Complete!');
    console.log(` Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error(' Error:', error);
    process.exit(1);
  }
}

migrate();